//login
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
//logout
export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR"
//getbot
export const GET_BOT = "GET_BOT"
export const GET_BOT_SUCCESS = "GET_BOT_SUCCESS"
export const GET_BOT_ERROR = "GET_BOT_ERROR"
//deletebot
export const DELETE_BOT = "DELETE_BOT"
export const DELETE_BOT_SUCCESS = "DELETE_BOT_SUCCESS"
export const DELETE_BOT_ERROR = "DELETE_BOT_ERROR"
//uploadbot
export const UPLOAD_BOT = "UPLOAD_BOT"
export const UPLOAD_BOT_SUCCESS = "UPLOAD_BOT_SUCCESS"
export const UPLOAD_BOT_ERROR = "UPLOAD_BOT_ERROR"
//activebot
export const ACTIVE_BOT = "ACTIVE_BOT"
export const ACTIVE_BOT_SUCCESS = "ACTIVE_BOT_SUCCESS"
export const ACTIVE_BOT_ERROR = "ACTIVE_BOT_ERROR"
//GET activebot
export const GET_ACTIVE_BOT = "GET_ACTIVE_BOT"
export const GET_ACTIVE_BOT_SUCCESS = "GET_ACTIVE_BOT_SUCCESS"
export const GET_ACTIVE_BOT_ERROR = "GET_ACTIVE_BOT_ERROR"
//DELETE activated bot
export const DELETE_ACTIVATED_BOT = "DELETE_ACTIVATED_BOT"
export const DELETE_ACTIVATED_BOT_SUCCESS = "DELETE_ACTIVATED_BOT_SUCCESS"
export const DELETE_ACTIVATED_BOT_ERROR = "DELETE_ACTIVATED_BOT_ERROR"